version: "3.8"

networks:
  restaurant:
      external: true

services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
    ports:
      - "${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - restaurant
  app:
    platform: linux/amd64
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - restaurant
    depends_on:
      - postgres
    entrypoint: >
      sh -c "
        rm requirements.txt
        echo Apllying alembic migration...
        alembic upgrade head
        echo Starting uvicorn server...
        python -m uvicorn app.backend.main:app --host 0.0.0.0 --port 8080 --reload
      "

